MvcCv/Controllers/HobilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models;

namespace MvcCv.Controllers
{
    public class HobilerController : Controller
    {
        // GET: Hobiler
        MvcCvEntities db = new MvcCvEntities();
        public ActionResult Index()
        {
            var liste = db.TblInterests.ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(TblInterests x)
        {
            db.TblInterests.Add(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var rmv = db.TblInterests.Find(id);
            db.TblInterests.Remove(rmv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Güncelle(int id)
        {
            var bul = db.TblInterests.Find(id);
            return View(bul);
        }
        public ActionResult Güncelle2(TblInterests x)
        {
            var Güncelle = db.TblInterests.Find(x.Id);
            Güncelle.Interest = x.Interest;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcCv/Views/Hobiler/Ekle.cshtml
@model MvcCv.Models.TblInterests 
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">

    <label>Yetenek</label>
    @Html.TextBoxFor(x => x.Interest, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Kaydet</button>

</form>

MvcCv/Views/Hobiler/Güncelle.cshtml
@model MvcCv.Models.TblInterests
@{
    ViewBag.Title = "Güncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Güncelle2", "Hobiler", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })

    <label>Hobi</label>
    @Html.TextBoxFor(x => x.Interest, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcCv/Views/Hobiler/Index.cshtml
@using MvcCv.Models
@model List<TblInterests>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>

        <th>HOBİ</th>
        <th>İŞLEMLER</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>

            <td>@x.Interest</td>

            <td>
                <a href="/Hobiler/Sil/@x.Id" class="btn btn-info">Sil</a>

                <a href="/Hobiler/Güncelle/@x.Id" class="btn btn-primary">Güncelle</a>
            </td>
        </tr>

    }

</table>
<a href="/Hobiler/Ekle" class="btn btn-danger">Ekle</a>