MvcCv/Controllers/SertifikalarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models;
namespace MvcCv.Controllers
{
    public class SertifikalarController : Controller
    {
        // GET: Setifikalar
        MvcCvEntities db = new MvcCvEntities();
        public ActionResult Index()
        {
            var liste = db.TblCertificates.ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(TblCertificates x)
        {
            db.TblCertificates.Add(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var rmv = db.TblCertificates.Find(id);
            db.TblCertificates.Remove(rmv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Güncelle(int id)
        {
            var bul = db.TblCertificates.Find(id);
            return View("Güncelle",bul);
        }
        public ActionResult Güncelle2(TblCertificates x)
        {
            var Güncelle = db.TblCertificates.Find(x.Id);
            Güncelle.Certificate = x.Certificate;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcCv/Views/Sertifikalar/Ekle.cshtml
@model MvcCv.Models.TblCertificates
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">

    <label>Sertifika</label>
    @Html.TextBoxFor(x => x.Certificate, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Kaydet</button>

</form>

MvcCv/Views/Sertifikalar/Güncelle.cshtml
@model MvcCv.Models.TblCertificates
@{
    ViewBag.Title = "Güncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Güncelle2", "Sertifikalar", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })

    <label>Sertifika</label>
    @Html.TextBoxFor(x => x.Certificate, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcCv/Views/Sertifikalar/Index.cshtml
@using MvcCv.Models
@model List<TblCertificates>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


    <table class="table table-bordered">
        <tr>

            <th>SERTİFİKALAR</th>
            <th>İŞLEMLER</th>
        </tr>

        @foreach (var x in Model)
        {
            <tr>

                <td>@x.Certificate</td>

                <td>
                    <a href="/Sertifikalar/Sil/@x.Id" class="btn btn-info", onclick="return confirm('Silmek İstiyor musunuz?')">Sil</a>

                    <a href="/Sertifikalar/Güncelle/@x.Id" class="btn btn-primary">Güncelle</a>
                </td>
            </tr>

        }

    </table>
    <a href="/Sertifikalar/Ekle" class="btn btn-danger">Ekle</a>