MvcCv/Controllers/EğitimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCv.Models;

namespace MvcCv.Controllers
{
    public class EğitimController : Controller
    {
        // GET: Eğitim
        MvcCvEntities db = new MvcCvEntities();
        public ActionResult Index()
        {
            var liste = db.TblEducation.ToList();

            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(TblEducation x)
        {
            db.TblEducation.Add(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var rmv = db.TblEducation.Find(id);
            db.TblEducation.Remove(rmv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Güncelle(int id)
        {
            var bul = db.TblEducation.Find(id);
            return View("Güncelle", bul);
        }

        public ActionResult Güncelle2(TblEducation x)
        {
            var Güncelle = db.TblEducation.Find(x.Id);
            Güncelle.Title = x.Title;
            Güncelle.SubTitle = x.SubTitle;
            Güncelle.Department = x.Department;
            Güncelle.Gpa = x.Gpa;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcCv/Views/Eğitim/Ekle.cshtml
@model MvcCv.Models.TblEducation
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">

    <label>Kurum</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    <label>Fakülte</label>
    @Html.TextBoxFor(x => x.SubTitle, new { @class = "form-control" })
    <br />
    <label>Bölüm</label>
    @Html.TextBoxFor(x => x.Department, new { @class = "form-control" })
    <br />
    <label>Ortalama</label>
    @Html.TextBoxFor(x => x.Gpa, new { @class = "form-control" })

    <br />
    <button class="btn btn-warning">Kaydet</button>

</form>

MvcCv/Views/Eğitim/Güncelle.cshtml
@model MvcCv.Models.TblEducation
@{
    ViewBag.Title = "Güncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Güncelle2", "Eğitim", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
    <label>Kurum</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    <label>Görev</label>
    @Html.TextBoxFor(x => x.SubTitle, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Department, new { @class = "form-control" })
    <br />
    <label>Açıklama</label>
    @Html.TextBoxFor(x => x.Gpa, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcCv/Views/Eğitim/Index.cshtml
@using MvcCv.Models
@model List<TblEducation>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KURUM</th>
        <th>FAKÜLTE</th>
        <th>BÖLÜM</th>
        <th>ORTALAMA</th>
        <th>İŞLEMLER</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Title</td>
            <td>@x.SubTitle</td>
            <td>@x.Department</td>
            <td>@x.Gpa</td>

            <td>
                <a href="/Eğitim/Sil/@x.Id" class="btn btn-info">Sil</a>

                <a href="/Eğitim/Güncelle/@x.Id" class="btn btn-primary">Güncelle</a>
            </td>
        </tr>

    }

</table>
<a href="/Eğitim/Ekle" class="btn btn-danger">Ekle</a>